-- Run this once in the Supabase SQL Editor (after setup.sql and migration_2).
-- Adds real visitor tracking for the admin dashboard. One row per page load
-- -- simple and accurate, no analytics service needed. At personal-portfolio
-- traffic levels this table will stay tiny for years.

create table if not exists page_views (
    id bigint generated by default as identity primary key,
    viewed_at timestamptz not null default now()
);

alter table page_views enable row level security;

-- Any visitor's browser can log a view (that's what makes the count real).
drop policy if exists "Public can log a page view" on page_views;
create policy "Public can log a page view" on page_views
    for insert with check (true);

-- Only you can read the total -- visit counts stay private, not shown publicly.
drop policy if exists "Authenticated can read page views" on page_views;
create policy "Authenticated can read page views" on page_views
    for select using (auth.role() = 'authenticated');
