-- Run this once in the Supabase SQL Editor (after migration_7_liquid_metal.sql).
-- Adds the "Apps" content type: admin-managed list of apps (name + icon + Google Drive
-- download link), shown on the new apps.html page. Reuses the existing 'project-images'
-- storage bucket for icons (already public with the right policies) instead of creating a
-- new bucket. Additive and safe to re-run.

create table if not exists apps (
    id bigint generated by default as identity primary key,
    name text not null,
    icon_url text,
    drive_url text not null,
    sort_order int not null default 0,
    created_at timestamptz not null default now()
);

alter table apps enable row level security;

drop policy if exists "Public can read apps" on apps;
create policy "Public can read apps" on apps
    for select using (true);

drop policy if exists "Authenticated can manage apps" on apps;
create policy "Authenticated can manage apps" on apps
    for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
