-- Run this once in the Supabase SQL Editor (after setup.sql, migration_2, migration_3).
-- Makes the rest of the site editable from admin.html: hero text, contact info,
-- footer, social links, experience, education, testimonials. Seeds site_content
-- and social_links with what's currently hardcoded so nothing changes visually
-- until you edit something. Experience/education/testimonials start empty --
-- those sections stay hidden on the public site until you add real entries.

-- ---------- site_content: single key/value pairs for one-off text ----------
create table if not exists site_content (
    key text primary key,
    value text not null default ''
);

alter table site_content enable row level security;

drop policy if exists "Public can read site content" on site_content;
create policy "Public can read site content" on site_content
    for select using (true);

drop policy if exists "Authenticated can manage site content" on site_content;
create policy "Authenticated can manage site content" on site_content
    for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

insert into site_content (key, value) values
    ('hero_badge', 'Available for hire'),
    ('hero_heading', 'Building Fast, Reliable'),
    ('hero_heading_highlight', 'Web Experiences.'),
    ('hero_bio', 'Frontend Developer specializing in modern web and mobile applications, and a Fiverr Level 2 Seller providing professional Telegram moderation and community management. I use an AI-assisted workflow — Claude, ChatGPT, and Cursor — to build and ship faster.'),
    ('hero_button_text', 'Download Resume'),
    ('primary_cta_link', 'https://www.fiverr.com/rafikhand1'),
    ('resume_url', ''),
    ('about_eyebrow', 'About'),
    ('about_heading', 'Who I Am'),
    ('about_text', 'I''m Ehsanul Karim Tanjil, a Computer Science & Engineering student at BUBT and a Fiverr Level 2 Seller with 65+ reviews and a 4.9★ rating. I build fast, reliable web experiences using an AI-assisted workflow, and manage Telegram communities with a focus on safety and engagement.'),
    ('work_heading', 'My Work'),
    ('skills_eyebrow', 'Skills'),
    ('skills_heading', 'Tools & Technologies I'),
    ('skills_heading_highlight', 'Use'),
    ('experience_heading', 'Experience'),
    ('education_heading', 'Education'),
    ('testimonials_heading', 'What Clients Say'),
    ('contact_heading', 'Get In Touch'),
    ('contact_text', 'Have a project in mind or need a Telegram community managed? Send an email — I read every message.'),
    ('contact_email', 'ehsanultanjil@gmail.com'),
    ('footer_name', 'Tanjil'),
    ('footer_copyright', '© 2026 Ehsanul Karim Tanjil.')
on conflict (key) do nothing;

-- ---------- resume file storage (uploaded from admin.html Site Text form) ----------
insert into storage.buckets (id, name, public)
values ('resume-files', 'resume-files', true)
on conflict (id) do nothing;

drop policy if exists "Public can view resume files" on storage.objects;
create policy "Public can view resume files"
on storage.objects for select
using (bucket_id = 'resume-files');

drop policy if exists "Authenticated can upload resume files" on storage.objects;
create policy "Authenticated can upload resume files"
on storage.objects for insert
with check (bucket_id = 'resume-files' and auth.role() = 'authenticated');

drop policy if exists "Authenticated can update resume files" on storage.objects;
create policy "Authenticated can update resume files"
on storage.objects for update
using (bucket_id = 'resume-files' and auth.role() = 'authenticated');

drop policy if exists "Authenticated can delete resume files" on storage.objects;
create policy "Authenticated can delete resume files"
on storage.objects for delete
using (bucket_id = 'resume-files' and auth.role() = 'authenticated');

-- ---------- social_links: footer icon/text row ----------
create table if not exists social_links (
    id bigint generated by default as identity primary key,
    label text not null,
    url text not null,
    sort_order int not null default 0,
    created_at timestamptz not null default now()
);

alter table social_links enable row level security;

drop policy if exists "Public can read social links" on social_links;
create policy "Public can read social links" on social_links
    for select using (true);

drop policy if exists "Authenticated can manage social links" on social_links;
create policy "Authenticated can manage social links" on social_links
    for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

insert into social_links (label, url, sort_order) values
    ('GitHub', '#', 1),
    ('LinkedIn', '#', 2),
    ('Fiverr', 'https://www.fiverr.com/rafikhand1', 3);

-- ---------- experience: work history timeline ----------
create table if not exists experience (
    id bigint generated by default as identity primary key,
    title text not null,
    organization text not null default '',
    start_date text not null default '',
    end_date text not null default '',
    description text not null default '',
    image_url text,
    sort_order int not null default 0,
    created_at timestamptz not null default now()
);
alter table experience add column if not exists image_url text;

alter table experience enable row level security;

drop policy if exists "Public can read experience" on experience;
create policy "Public can read experience" on experience
    for select using (true);

drop policy if exists "Authenticated can manage experience" on experience;
create policy "Authenticated can manage experience" on experience
    for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- ---------- education ----------
create table if not exists education (
    id bigint generated by default as identity primary key,
    degree text not null,
    short_name text not null default '',
    institution text not null default '',
    start_date text not null default '',
    end_date text not null default '',
    description text not null default '',
    sort_order int not null default 0,
    created_at timestamptz not null default now()
);
alter table education add column if not exists short_name text not null default '';

alter table education enable row level security;

drop policy if exists "Public can read education" on education;
create policy "Public can read education" on education
    for select using (true);

drop policy if exists "Authenticated can manage education" on education;
create policy "Authenticated can manage education" on education
    for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- ---------- testimonials ----------
create table if not exists testimonials (
    id bigint generated by default as identity primary key,
    client_name text not null,
    quote text not null default '',
    rating int not null default 5,
    sort_order int not null default 0,
    created_at timestamptz not null default now()
);

alter table testimonials enable row level security;

drop policy if exists "Public can read testimonials" on testimonials;
create policy "Public can read testimonials" on testimonials
    for select using (true);

drop policy if exists "Authenticated can manage testimonials" on testimonials;
create policy "Authenticated can manage testimonials" on testimonials
    for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
