-- Run this once in the Supabase SQL Editor (after migration_9_video_bg.sql).
-- Adds the "background_videos" table so the admin can manage multiple background
-- videos with custom display titles, sort order, and visibility.
-- Reuses the existing 'project-images' storage bucket for video uploads.

create table if not exists background_videos (
    id bigint generated by default as identity primary key,
    title text not null,
    video_url text not null,
    sort_order int not null default 0,
    visible boolean not null default true,
    created_at timestamptz not null default now()
);

alter table background_videos enable row level security;

drop policy if exists "Public can read background videos" on background_videos;
create policy "Public can read background videos" on background_videos
    for select using (true);

drop policy if exists "Authenticated can manage background videos" on background_videos;
create policy "Authenticated can manage background videos" on background_videos
    for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
