-- Run this once in the Supabase SQL Editor (after setup.sql, migration_2, migration_3, migration_4).
-- Adds the columns/settings needed for the redesigned admin panel: extra
-- project/experience/education/testimonial fields, visibility toggles,
-- drag-reorder support (sort_order already exists on every table), and new
-- site-wide settings (SEO, favicon/logo, maintenance mode, analytics,
-- visual-effect toggles, extra contact fields). Every statement here is
-- additive and safe to re-run.

-- ---------- projects: separate Website/GitHub links, visibility, featured ----------
alter table projects add column if not exists github_url text;
alter table projects add column if not exists visible boolean not null default true;
alter table projects add column if not exists featured boolean not null default false;

-- ---------- skills: experience level ----------
alter table skills add column if not exists level text not null default '';

-- ---------- experience: company website ----------
alter table experience add column if not exists website_url text;

-- ---------- education: grade/result ----------
alter table education add column if not exists grade text not null default '';

-- ---------- testimonials: role, company, photo, visibility ----------
alter table testimonials add column if not exists position text not null default '';
alter table testimonials add column if not exists company text not null default '';
alter table testimonials add column if not exists photo_url text;
alter table testimonials add column if not exists visible boolean not null default true;

-- ---------- social_links: visibility ----------
alter table social_links add column if not exists visible boolean not null default true;

-- ---------- resume_clicks: real "Downloads" stat on the dashboard ----------
create table if not exists resume_clicks (
    id bigint generated by default as identity primary key,
    clicked_at timestamptz not null default now()
);

alter table resume_clicks enable row level security;

drop policy if exists "Public can log a resume click" on resume_clicks;
create policy "Public can log a resume click" on resume_clicks
    for insert with check (true);

drop policy if exists "Authenticated can read resume clicks" on resume_clicks;
create policy "Authenticated can read resume clicks" on resume_clicks
    for select using (auth.role() = 'authenticated');

-- ---------- site_content: new settings (defaults keep current behavior) ----------
insert into site_content (key, value) values
    ('seo_title', 'Tanjil'),
    ('seo_description', 'Frontend Developer and Fiverr Level 2 Seller — portfolio of Ehsanul Karim Tanjil.'),
    ('favicon_url', ''),
    ('logo_url', ''),
    ('maintenance_mode', 'false'),
    ('ga_id', ''),
    ('gsc_verification', ''),
    ('particles_enabled', 'true'),
    ('cursor_light_enabled', 'true'),
    ('orbit_enabled', 'true'),
    ('preloader_enabled', 'true'),
    ('contact_phone', ''),
    ('contact_address', ''),
    ('contact_whatsapp', ''),
    ('contact_form_email', '')
on conflict (key) do nothing;
