-- Run this once in your Supabase project's SQL Editor (Dashboard -> SQL Editor -> New query).
-- Creates the projects/skills tables, locks them down with Row Level Security,
-- and seeds them with the content that's currently hardcoded on the site,
-- so nothing changes visually until you actually edit something in admin.html.

create table if not exists projects (
    id bigint generated by default as identity primary key,
    title text not null,
    description text not null default '',
    link_url text,
    tag text not null default 'COMING SOON',
    sort_order int not null default 0,
    created_at timestamptz not null default now()
);

create table if not exists skills (
    id bigint generated by default as identity primary key,
    category text not null,
    icon text not null default 'code', -- a Material Symbols icon name, e.g. code / palette / movie / groups
    name text not null,
    sort_order int not null default 0,
    created_at timestamptz not null default now()
);

alter table projects enable row level security;
alter table skills enable row level security;

-- Anyone (including logged-out visitors) can read -- this is what makes the
-- public site work without a login.
create policy "Public can read projects" on projects
    for select using (true);

create policy "Public can read skills" on skills
    for select using (true);

-- Only a logged-in user can write. Since sign-ups aren't exposed anywhere
-- (you create your one admin account manually in the Supabase dashboard),
-- "authenticated" effectively means "you".
create policy "Authenticated can manage projects" on projects
    for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create policy "Authenticated can manage skills" on skills
    for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- Seed data matching what's currently hardcoded on the site.
insert into projects (title, description, tag, sort_order) values
    ('Project Title', 'Short project description goes here.', 'COMING SOON', 1),
    ('Project Title', 'Short project description goes here.', 'COMING SOON', 2),
    ('Project Title', 'Short project description goes here.', 'COMING SOON', 3);

insert into skills (category, icon, name, sort_order) values
    ('Development', 'code', 'Claude', 1),
    ('Development', 'code', 'ChatGPT', 2),
    ('Development', 'code', 'Cursor', 3),
    ('Development', 'code', 'React.js', 4),
    ('Development', 'code', 'Next.js', 5),
    ('Development', 'code', 'TypeScript', 6),
    ('Development', 'code', 'Tailwind CSS', 7),
    ('Development', 'code', 'Node.js', 8),
    ('Development', 'code', 'PostgreSQL', 9),
    ('Development', 'code', 'Git & GitHub', 10),
    ('Design', 'palette', 'Figma', 1),
    ('Design', 'palette', 'Adobe Photoshop', 2),
    ('Design', 'palette', 'UI/UX Design', 3),
    ('Video Editing', 'movie', 'Premiere Pro', 1),
    ('Video Editing', 'movie', 'After Effects', 2),
    ('Community & Client Work', 'groups', 'Telegram Moderation', 1),
    ('Community & Client Work', 'groups', 'Community Management', 2),
    ('Community & Client Work', 'groups', 'Fiverr Freelancing', 3);
